[package]
	edition = "2021"
	name = "fmt-interspersed"
	rust-version = "1.56"
	version = "0.1.2"

	description = "A no-std crate to write an iterator's items, interspersed with a separator, to a destination"
	license = "MIT"

[lib]
	crate-type = ["rlib"]
